### ISSUE TITLE
Order of apt operations on Debian

### ISSUE THREAD

**Issue by tszym** [samdoran/ansible-role-gitlab#11]
Hi,

There is an issue when executing this role on Debian Jessie. I tested this on version `3.1.1` of this role.

[The repo file is added to the system](https://github.com/samdoran/ansible-role-gitlab/blob/3.1.1/tasks/main.yml#L19) before [the inclusion of the Debian specific tasks file](https://github.com/samdoran/ansible-role-gitlab/blob/3.1.1/tasks/main.yml#L37) and the `apt` tasks.
At this point, the role will failt at [the cache update of the `apt` task](https://github.com/samdoran/ansible-role-gitlab/blob/3.1.1/tasks/install-Debian.yml#L9) because the `apt-transport-https` package is not installed yet, and apt cannot use the previously added repo. It [will be installed too late](https://github.com/samdoran/ansible-role-gitlab/blob/3.1.1/tasks/install-Debian.yml#L15).

Ansible output:
```
TASK [samdoran.gitlab : DEBIAN | Install support packages] *********************
fatal: [debian]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
```

On the host:
```
user@jessie:~$ sudo apt-get update
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
```

The issue is solved by installing the `apt-transport-https` package before calling this role.

**Comment by samdoran** [comment]
Thanks for bringing this to my attention. Looking into it now.

**Comment by samdoran** [comment]
Looks like setting `update_cache: no` on the `Install support packages` task is sufficient to fix this.
