### ISSUE TITLE
Dont make gitlab ci user unless we specifiy gitlab_ci_enabled True

### ISSUE THREAD

**Issue by farridav** [samdoran/ansible-role-gitlab#5]
This role is currently creating the gitlab ci user even if `gitlab_ci_enabled` is not set...  perhaps we could add a conditional to this?

There are some other gitlab-ci packages that also get installed regardless e.g `gitlab-ci-rake`, `gitlab-ci-rails`

Thanks for the great work :)

**Comment by samdoran** [comment]
@farridav This is legacy code I'm planning to rip out since the CI parts are much more integrated into GitLab now and less separate.
