### ISSUE TITLE
Wrong name of role in README

### ISSUE THREAD

**Issue by marcinpraczko** [samdoran/ansible-role-gitlab#6]
There is not valid name in examples playbooks in README. Copy / Paste playbook ends with ansible errors:

``` bash
ERROR: cannot find role in ... {Paths for roles}
```

**Comment by samdoran** [comment]
@marcinpraczko The default role name is `samdoran.gitlab`. I'm wondering if maybe it didn't get installed correctly in your role directory? The easiest way to ensure it gets put in the proper place is to specify the installation path using `-p`. E.g., `ansible-galaxy install samdoran.gitlab -p roles/`.

```
project
└── roles
    └── samdoran.gitlab
```
